datasource_driver: com.mysql.cj.jdbc.Driver
datasource_url: jdbc:mysql://192.168.1.254:3306/monitor?useSSL=false&characterEncoding=utf8&serverTimeZone=GMT%2B8
datasource_username: root
datasource_password: ophyer

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#logging:
#  level:
#    com:
#      coder:
#        monitor:
#          mapper: debug